# Generated by Django 5.0.3 on 2024-08-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callproduct',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Quant. Disponível'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quant. Pedida'),
        ),
    ]
