# Generated by Django 4.2.3 on 2024-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('denied', 'Negado'), ('delivered', 'Entregue')], default='pending', max_length=10),
        ),
    ]
