name: Deploy Django

# Só roda quando um PR é fechado no branch main
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
  # Só roda se além do PR fechado, também houve um merge.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH # Cria as chaves locais a partir de segredos salvos no Github
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_KEY_PRIV }}" > ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_KEY_PUB }}" > ~/.ssh/id_ed25519.pub
        chmod 600 ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519.pub
        ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
    - name: Run Deployment
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SERVER }} "bash deploy.sh cooppotengi"
      env:
        ACTIONS_RUNNER_DEBUG: false
